<a href="https://colab.research.google.com/github/Ghan539/Python4DataScientist/blob/main/numpy/session_15_practice_numpy_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.random.randint(1,100,15)
print(a)

[16 82 86 39 21 26  7 40 14 33 72 71 80 73 81]


In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
print(b)


[[22 94 41 70]
 [64 11 95 41]
 [73 84 14 96]
 [ 2 99 48 56]
 [21 46 18 61]
 [41 98 34 62]]


In [ ]:
# np.cumsum

print(np.cumsum(a))

[ 16  98 184 223 244 270 277 317 331 364 436 507 587 660 741]


In [ ]:
print(np.cumsum(b))

[  22  116  157  227  291  302  397  438  511  595  609  705  707  806
  854  910  931  977  995 1056 1097 1195 1229 1291]


In [ ]:
print(np.cumsum(b,axis=0))

[[ 22  94  41  70]
 [ 86 105 136 111]
 [159 189 150 207]
 [161 288 198 263]
 [182 334 216 324]
 [223 432 250 386]]


In [ ]:
print(np.cumsum(b,axis=1))

[[ 22 116 157 227]
 [ 64  75 170 211]
 [ 73 157 171 267]
 [  2 101 149 205]
 [ 21  67  85 146]
 [ 41 139 173 235]]


In [ ]:
# np.cumprod

print(np.cumprod(a))


[                  16                 1312               112832
              4400448             92409408           2402644608
          16818512256         672740490240        9418366863360
      310806106490880    22378039667343360  1588840816381378560
 -2019943205456576512   118098591346327552 -8880758174657019904]


In [ ]:
print(np.cumprod(b))

[                  22                 2068                84788
              5935160            379850240           4178352640
         396943500800       16274683532800     1188051897894400
    99796359423129600  1397149031923814400  4999098548719321088
 -8448546976270909440 -6302667333890211840 -7380126847377342464
 -7458733831521042432 -9059457872265478144  7540051571107692544
  6593719763971604480 -3611464019342262272  -496072203356340224
  6725156292207312896  7294385050534019072 -8916728709629607936]


In [ ]:
print(np.cumprod(b,axis=0))

[[         22          94          41          70]
 [       1408        1034        3895        2870]
 [     102784       86856       54530      275520]
 [     205568     8598744     2617440    15429120]
 [    4316928   395542224    47113920   941176320]
 [  176994048 38763137952  1601873280 58352931840]]


In [ ]:
# percentile
print(a)

print(np.percentile(a,100))
print(np.percentile(a,50))
print(np.percentile(a,0))

[16 82 86 39 21 26  7 40 14 33 72 71 80 73 81]
86.0
40.0
7.0


In [ ]:
# np.histogram ==count frequency
print(a)
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])


[16 82 86 39 21 26  7 40 14 33 72 71 80 73 81]
(array([1, 4, 3, 7]), array([  0,  10,  30,  70, 100]))


In [ ]:
# corrcoef

salary=np.array([20000,40000,25000,35000,60000])
experience=np.array([1,3,2,4,2])
print(np.corrcoef(salary,experience))

[[1.         0.25344572]
 [0.25344572 1.        ]]


In [ ]:
# np.isin

print(a)
items=[10,20,30,40,50,60,70,80,90,100]

print(a[np.isin(a,items)])

[16 82 86 39 21 26  7 40 14 33 72 71 80 73 81]
[40 80]


In [ ]:
# flip

print(a)
print(np.flip(a))

[16 82 86 39 21 26  7 40 14 33 72 71 80 73 81]
[81 73 80 71 72 33 14 40  7 26 21 39 86 82 16]


In [ ]:
# flip rowise
print(b)
print(np.flip(b))
print(np.flip(b,axis=0))

[[22 94 41 70]
 [64 11 95 41]
 [73 84 14 96]
 [ 2 99 48 56]
 [21 46 18 61]
 [41 98 34 62]]
[[62 34 98 41]
 [61 18 46 21]
 [56 48 99  2]
 [96 14 84 73]
 [41 95 11 64]
 [70 41 94 22]]
[[41 98 34 62]
 [21 46 18 61]
 [ 2 99 48 56]
 [73 84 14 96]
 [64 11 95 41]
 [22 94 41 70]]


In [68]:
# np.put == replace elements in array

print(a)
np.put(a,[0,1],[110,234])
print(a)

[110 234  86  39  21  26   7  40  14  33  72  71  80  73  81]
[110 234  86  39  21  26   7  40  14  33  72  71  80  73  81]


In [69]:
# np.delete

print(a)
np.delete(a,[0,1,2])
print(a)

[110 234  86  39  21  26   7  40  14  33  72  71  80  73  81]
[110 234  86  39  21  26   7  40  14  33  72  71  80  73  81]


In [ ]:
# set functions

# np.union1d
# np.intersect1d
# np.setdiff1d
# np.setxor1d
# np.in1d

m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

un=np.union1d(m,n)
print(un)
ins=np.intersect1d(m,n)
print(ins)

diff=np.setdiff1d(m,n)
print(diff)

diff=np.setdiff1d(n,m)
print(diff)

xor=np.setxor1d(m,n)
print(xor)

# in1d

print(m[np.in1d(m,2)])

In [72]:
# clip

print(a)

np.clip(a,a_min=25,a_max=75)

[110 234  86  39  21  26   7  40  14  33  72  71  80  73  81]


array([75, 75, 75, 39, 25, 26, 25, 40, 25, 33, 72, 71, 75, 73, 75])