<a href="https://colab.research.google.com/github/Ghan539/Python4DataScientist/blob/main/numpy/session13_numpy%20fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy
import numpy as np
a=np.array([1,2,3,4,5,6])

print(a)

# 2d array (metric)

b=np.array([[2,4],[24,64]])
print(b)

# 3d array

c=np.array([[[23,34,54,56],[23,45,65,23],[67,79,98,99],[34,56,78,87]]])
print(c)


# dtype
np.array([22,34,45],dtype=complex)




[1 2 3 4 5 6]
[[ 2  4]
 [24 64]]
[[[23 34 54 56]
  [23 45 65 23]
  [67 79 98 99]
  [34 56 78 87]]]


array([22.+0.j, 34.+0.j, 45.+0.j])

In [ ]:
# arange

d=np.arange(1,123,3)
print(d)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122]


In [ ]:
# with reshape

e=np.arange(1,13).reshape(3,4)
print(e)

# with reshape
f=np.arange(16).reshape(2,2,4)
print(f)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# np.ones

g=np.ones((4,4))
print(g)

# np.zeros

h=np.zeros((5,5))
print(h)


# np.random

i=np.random.random((3,4))
print(i)

In [ ]:
# np.linespace

j=np.linspace(0,2,10,dtype=float)
print(j)

# np.identity

k=np.identity(6)
print(k)

# array attributes
b1=np.arange(10,dtype=int)
b2=np.arange(12,dtype=float)
b3=np.arange(32).reshape(2,2,4,2)


print(b1)
print(b2)
print(b3)

In [ ]:
# # np.linespace

# j=np.linspace(0,2,10,dtype=float)
# print(j)

# # np.identity

# k=np.identity(6)
# print(k)

# array attributes
b1=np.arange(10,dtype=int)
b2=np.arange(12,dtype=complex).reshape(3,4)
b3=np.arange(40).reshape(2,2,5,2)


print(b1)
print(b2)
print(b3)

# ndim
print(b1.ndim)
print(b2.ndim)
print(b3.ndim)

# shape

print(b1.shape)
print(b2.shape)
print(b3.shape)

# size

print(b1.size)
print(b2.size)
print(b3.size)


# itemsize

print(b1.itemsize)
print(b2.itemsize)
print(b3.itemsize)

# dtype

print(b1.dtype)
print(b2.dtype)
print(b3.dtype)


# astype ----changing data type
b2.astype(np.int32)

print(b2)


#scalar operations

# arithmetic
b2**2
print(b2**2)

# relational

print(b3==32)

# vector operations

# arithmetic operations

c1=np.arange(1,5)
c2=np.arange(1,5)
print(c1)
print(c2)
prod=(c1*c2).reshape(2,2)
print(prod)


In [ ]:

d1=np.random.random((3,3))
d1=np.round(d1*100 )
print(d1)

# max
print(np.max(d1))

#min
print(np.min(d1))

# prod
print(np.prod(d1))

# sum
print(np.sum(d1))

# rows max
# 0 col , 1 row


print(np.max(d1,axis=1))
print(np.max(d1,axis=0))

In [ ]:
ar1=np.arange(1,10).reshape(3,3)
print(ar1)

print(np.max(ar1))
print(np.min(ar1))
print(np.prod(ar1))
print(np.sum(ar1))

print("row",np.max(ar1,axis=1))
print("column",np.max(ar1,axis=0))
print("column",np.max(ar1,axis=0))
print("prod",np.prod(ar1,axis=0))

# trigonometric functions

print(np.sin(ar1))

# dot product

arr1=np.arange(12).reshape(3,4)
arr2=np.arange(12).reshape(4,3)
print(arr1)
print(arr2)
print(np.dot(arr1,arr2))


#   log and exponents

arr3=([[4.72783947e+18, 1.44625706e+12, 6.83767123e+30],
       [5.32048241e+11, 2.45124554e+40, 4.31123155e+15],
       [2.90488497e+13, 6.56599691e+07, 1.09663316e+03]])

r=arr3.reshape((3,3))
print(r)

In [78]:
import numpy as np


# array indexing

x1=np.arange(10)
x2=np.arange(12).reshape((3,4))
x3=np.arange(8).reshape((2,2,2))

print(x1)
print(x2)
print(x3)


print(x1[2])
print(x2[1,1])
print(x3[0,1,1])
print(x3[1,1,0])

print(x1[1:5])


# slicing
print(x2)
# 1st row
print(x2[0,: ])

# 1st column
print(x2[:,0])

#3rd column
print(x2[:,2])

# 5,6
# 9,10
print(x2[1:,1:3])

# 0      3
# 8      11

print(x2[0::2,0::3])

#  1    3
#  9    11

print(x2[::2,1::2])

# 4    7

print(x2[1,::3])


# 1 2 3
# 5 6 7

print(x2[:2,1:])

# 1   3
# 5   7

print(x2[0:2,1::2])




[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
2
5
3
6
[1 2 3 4]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[0 4 8]
[ 2  6 10]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[4 7]
[[1 2 3]
 [5 6 7]]
[[1 3]
 [5 7]]


In [7]:
# slicing in 3d

a3=np.arange(27).reshape(3,3,3)

print(a3)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [9]:
print(a3[1])
print(a3[::2])


[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [10]:
# 3  4  5

print(a3[0,1,:])

[3 4 5]


In [17]:
# 10
# 13
# 16

print(a3[1,:,1])

[10 13 16]


In [19]:
# 22  23
# 35  26

print(a3[2,1:,1:])

[[22 23]
 [25 26]]


In [28]:
# tricky
# 0  2
# 18 20

# print(a3[[0,0,0::2],[2,0,::2]])

# print(a3[0,0,0::2])
# print(a3[2,0,::2])

print(a3[::2,0,::2])

[[ 0  2]
 [18 20]]


In [31]:
# /iterating


print(x1)
print(x2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [34]:
for i in x1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [39]:
for i in x2:
  print(i ,"-")

[0 1 2 3] -
[4 5 6 7] -
[ 8  9 10 11] -


In [40]:
for i in a3:
  print(i)



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [42]:
for i in np.nditer(a3):
  print(i ,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

In [48]:
# reshape
# transpose
# ravel


# transpose
print(x2)
tr=np.transpose(x2)
print(tr)

# method 2

tr2=x2.T
print(tr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [52]:
# ravel = convert multidimensional array to 1D

rr=x2.ravel()
print(rr)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [53]:
print(a3)
print(a3.ravel())

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [58]:
# stacking (jodna)

# horizontal stacking

x4=np.arange(12).reshape(3,4)
x5=np.arange(12,24).reshape(3,4)

print(x4)
print(x5)
np.hstack((x4,x5,x4))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [61]:
# horizontal stacking

np.vstack((x4,x5,x4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
# horizontal stacking

x4=np.arange(18).reshape(3,6)
x5=np.arange(12,24).reshape(3,4)

print(x4)
print(x5)
np.hstack((x4,x5))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 0,  1,  2,  3,  4,  5, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 11, 16, 17, 18, 19],
       [12, 13, 14, 15, 16, 17, 20, 21, 22, 23]])

In [77]:
# splitting

print(x2)
np.hsplit(x2,4,)

print(np.vsplit(x2,3))






[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
